import {useState} from 'react'
import {useOperations} from '../../hooks/useOperations'
import {vehicles,vehiclePayload,drivers,driverPayload,refId,operationRefreshScopes} from '../../utils/operations'
import {VEHICLE_TYPES,VEHICLE_STATUSES} from '../../utils/constants'
import {formatVehicleType,formatStatus} from '../../utils/formatters'
import StatusBadge from '../ui/StatusBadge'
import Button from '../ui/Button'
import {OperationsHeader,DataTable,EditForm,ConfirmDialog,Modal,ActionForm,SelectField,LoadState} from './OperationsUI'
const options=values=>values.map(value=>[value,formatStatus(value)])
export function VehiclesManager() {
 const [status,setStatus]=useState('');const [type,setType]=useState('');const [edit,setEdit]=useState(null);const [deactivate,setDeactivate]=useState(null)
 const state=useOperations('vehicles',{...(status?{status}:{}),...(type?{type}:{})})
 const close=()=>setEdit(null)
 const fields=[{name:'registrationNumber',label:'Registration number',required:true},{name:'type',label:'Type',options:VEHICLE_TYPES.map(v=>[v,formatVehicleType(v)]),disabled:edit?.status==='assigned'},{name:'capacity',label:'Capacity (kg)',type:'number',min:'0.000001',step:'any',required:true,disabled:edit?.status==='assigned'},{name:'status',label:'Status',options:options(edit?._id?({available:['available','maintenance',...(edit.currentDriverId?[]:['inactive'])],maintenance:['maintenance','available',...(edit.currentDriverId?[]:['inactive'])],inactive:['inactive','available'],assigned:['assigned']}[edit.status]):['available','maintenance','inactive'])}]
 return <div className="page-stack"><OperationsHeader title="Vehicles" state={state}><Button onClick={()=>setEdit({type:'van',capacity:'',registrationNumber:'',status:'available'})}>Create vehicle</Button></OperationsHeader><div className="operations-filters"><SelectField label="Status" options={ [['','All statuses'],...options(VEHICLE_STATUSES)]} value={status} onChange={e=>setStatus(e.target.value)}/><SelectField label="Type" options={ [['','All types'],...VEHICLE_TYPES.map(v=>[v,formatVehicleType(v)])]} value={type} onChange={e=>setType(e.target.value)}/></div><LoadState state={state}><DataTable rows={state.data?.vehicles||[]} empty="No vehicles found" columns={[
 ['Registration',v=>v.registrationNumber],['Type',v=>formatVehicleType(v.type)],['Capacity',v=>v.capacity+' kg'],['Status',v=><StatusBadge status={v.status}/>],['Driver link',v=>v.currentDriverId?'Linked':'Not linked'],['Actions',v=><div className="customer-actions"><Button variant="quiet" onClick={()=>setEdit(v)}>Edit</Button><Button variant="quiet" disabled={v.status==='inactive'} onClick={()=>setDeactivate(v)}>Deactivate</Button></div>]
 ]}/></LoadState>{edit&&<EditForm title={edit._id?'Edit vehicle':'Create vehicle'} fields={fields} initial={edit} onClose={close} refreshScopes={operationRefreshScopes.vehicle} submit={values=>edit._id?vehicles.updateVehicle(edit._id,vehiclePayload(values)):vehicles.createVehicle(vehiclePayload(values))}/>}{deactivate&&<ConfirmDialog title={'Deactivate vehicle '+deactivate.registrationNumber+'?'} message="This marks the vehicle inactive. Assigned or linked vehicles cannot be deactivated." submit={()=>vehicles.deactivateVehicle(deactivate._id)} refreshScopes={operationRefreshScopes.vehicle} onClose={()=>setDeactivate(null)}/>}</div>
}
function LinkVehicle({driver,onClose}) {
 const state=useOperations('vehicles',{status:'available'});const [vehicleId,setVehicle]=useState('')
 return <Modal title="Link driver to vehicle" onClose={onClose}><LoadState state={state}><ActionForm submit={()=>drivers.assignVehicle(driver._id,{vehicleId})} onDone={onClose} refreshScopes={operationRefreshScopes.driver} label="Link vehicle">{fieldErrors=><><p>Choose an available, unlinked vehicle. Active work may prevent linkage.</p><SelectField label="Vehicle" error={fieldErrors.vehicleId} required value={vehicleId} onChange={e=>setVehicle(e.target.value)} options={ [['','Choose vehicle'],...(state.data?.vehicles||[]).filter(v=>!v.currentDriverId).map(v=>[v._id,v.registrationNumber+' · '+v.capacity+' kg'])]}/></>}</ActionForm></LoadState></Modal>
}
export function DriversManager() {
 const [available,setAvailable]=useState('');const [linked,setLinked]=useState('');const [edit,setEdit]=useState(null);const [link,setLink]=useState(null);const [unlink,setUnlink]=useState(null)
 const state=useOperations('drivers',{...(available?{available}:{}),...(linked?{vehicleAssigned:linked}:{})})
 const fields=[...(!edit?._id?[{name:'userId',label:'Existing driver User ID',required:true,pattern:'[a-fA-F0-9]{24}'}]:[]),{name:'licenseNumber',label:'License number',required:true,minLength:5,maxLength:40},{name:'phone',label:'Phone',required:true,minLength:7,maxLength:25},...(edit?._id?[{name:'isAvailable',label:'Allow new assignments',options:[['true','Available'],['false','Paused']]}]:[])]
 return <div className="page-stack"><OperationsHeader title="Drivers" state={state}><Button onClick={()=>setEdit({userId:'',licenseNumber:'',phone:''})}>Create driver profile</Button></OperationsHeader><div className="operations-filters"><SelectField label="Availability" options={ [['','All'],['true','Available'],['false','Paused']]} value={available} onChange={e=>setAvailable(e.target.value)}/><SelectField label="Vehicle linkage" options={ [['','All'],['true','Linked'],['false','Unlinked']]} value={linked} onChange={e=>setLinked(e.target.value)}/></div><LoadState state={state}><DataTable rows={state.data?.drivers||[]} empty="No driver profiles found" columns={[
 ['Driver',d=><>{d.userId?.name||'Account unavailable'}<small className="vehicle-type">{d.userId?.email}</small></>],['License',d=>d.licenseNumber],['Phone',d=>d.phone],['Availability',d=>d.isAvailable?'Available':'Paused'],['Vehicle',d=>d.vehicleId?.registrationNumber||'Unlinked'],['Actions',d=><div className="customer-actions"><Button variant="quiet" onClick={()=>setEdit({...d,isAvailable:String(d.isAvailable)})}>Edit</Button>{refId(d.vehicleId)?<Button variant="quiet" onClick={()=>setUnlink(d)}>Unlink vehicle</Button>:<Button variant="quiet" onClick={()=>setLink(d)}>Link vehicle</Button>}</div>]
 ]}/></LoadState>{edit&&<EditForm title={edit._id?'Edit driver':'Create driver profile'} initial={edit} fields={fields} note={!edit._id?'This creates an operational profile for an existing driver account. Ask for its User ID; no account directory is available.':undefined} refreshScopes={operationRefreshScopes.driver} submit={values=>edit._id?drivers.updateDriver(edit._id,driverPayload(values,true)):drivers.createDriver(driverPayload(values,false))} onClose={()=>setEdit(null)}/>}{link&&<LinkVehicle driver={link} onClose={()=>setLink(null)}/>}{unlink&&<ConfirmDialog title="Unlink vehicle?" message="This removes the driver/vehicle link. Active shipment work prevents unlinking." submit={()=>drivers.unassignVehicle(unlink._id)} refreshScopes={operationRefreshScopes.driver} onClose={()=>setUnlink(null)}/>}</div>
}
