import {useState} from 'react'
import {useOperations} from '../../hooks/useOperations'
import {trips,refId,eligibleShipments,shipmentOptions,tripActions,tripPayload,operationRefreshScopes} from '../../utils/operations'
import {TRIP_STATUSES} from '../../utils/constants'
import {formatStatus} from '../../utils/formatters'
import {TripCard} from '../driver/DriverComponents'
import Button from '../ui/Button'
import EmptyState from '../common/EmptyState'
import Field from '../ui/Field'
import {Modal,ActionForm,SelectField,LoadState,OperationsHeader,ConfirmDialog} from './OperationsUI'
function CreateTrip({onClose}) {
 const driverState=useOperations('drivers');const shipmentState=useOperations('shipments');const tripState=useOperations('trips');const vehicleState=useOperations('vehicles')
 const [driverId,setDriver]=useState('');const [selected,setSelected]=useState([]);const [date,setDate]=useState('')
 const driver=driverState.data?.drivers.find(d=>d._id===driverId)
 const options=shipmentOptions(shipmentState.data?.shipments||[],driver,tripState.data?.trips||[]);const eligible=eligibleShipments(shipmentState.data?.shipments||[],driver,tripState.data?.trips||[])
 const state=[driverState,shipmentState,tripState,vehicleState].find(s=>s.loading||s.error)||driverState
 return <Modal title="Create trip" onClose={onClose}><LoadState state={state}><ActionForm canSubmit={Boolean(driver)&&selected.length>0&&selected.every(id=>eligible.some(s=>s._id===id))} label="Create trip" refreshScopes={operationRefreshScopes.trip} onDone={onClose} submit={()=>{if(!driver||!selected.length||selected.some(id=>!eligible.some(s=>s._id===id)))throw new Error('Select eligible shipments');return trips.createTrip(tripPayload({driverId,vehicleId:refId(driver.vehicleId),shipmentIds:selected,date:date?new Date(date).toISOString():''}))}}>{fieldErrors=><><SelectField label="Driver and linked vehicle" error={fieldErrors.driverId} required value={driverId} onChange={e=>{setDriver(e.target.value);setSelected([])}} options={ [['','Choose driver'],...(driverState.data?.drivers||[]).filter(d=>d.vehicleId&&(vehicleState.data?.vehicles||[]).some(v=>v._id===refId(d.vehicleId)&&refId(v.currentDriverId)===d._id)).map(d=>[d._id,(d.userId?.name||'Driver')+' · '+d.vehicleId.registrationNumber])]}/><Field label="Trip date/time (optional, local time)" type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/><fieldset className="trip-selection"><legend>Eligible shipments</legend>{options.map(({shipment,reason})=><label key={shipment._id} className={reason?'trip-option-disabled':''}><input type="checkbox" disabled={Boolean(reason)} checked={selected.includes(shipment._id)} onChange={e=>setSelected(e.target.checked?[...selected,shipment._id]:selected.filter(id=>id!==shipment._id))}/>{shipment.pickupAddress} → {shipment.dropAddress} ({shipment.weight} kg){reason&&<small className="field-error">{reason}</small>}</label>)}{!options.length&&<p>No shipments are available for trip grouping.</p>}</fieldset>{fieldErrors.shipmentIds&&<p className="field-error" role="alert">{fieldErrors.shipmentIds}</p>}<p className="role-note">Select at least one compatible shipment. Disabled records explain why they cannot be grouped.</p></>}</ActionForm></LoadState></Modal>
}
export function TripsManager() {
 const [status,setStatus]=useState('');const [create,setCreate]=useState(false);const [action,setAction]=useState(null)
 const state=useOperations('trips',status?{status}:{})
 return <div className="page-stack"><OperationsHeader title="Trips" state={state}><Button onClick={()=>setCreate(true)}>Create trip</Button></OperationsHeader><SelectField label="Trip status" value={status} onChange={e=>setStatus(e.target.value)} options={ [['','All'],...TRIP_STATUSES.map(v=>[v,formatStatus(v)])]}/><LoadState state={state}>{state.data?.trips.length?<div className="shipment-grid">{state.data.trips.map(trip=><div key={trip._id}><TripCard trip={trip}/><div className="customer-actions">{tripActions(trip.status).map(next=><Button key={next} variant="quiet" onClick={()=>setAction({trip,next})}>{formatStatus(next)}</Button>)}</div></div>)}</div>:<EmptyState title="No trips yet" message="Create a trip from active assigned shipments."/>}</LoadState>{create&&<CreateTrip onClose={()=>setCreate(false)}/>} {action&&<ConfirmDialog title={'Set trip to '+formatStatus(action.next)+'?'} message={action.next==='cancelled'?'Cancellation ends this trip. It does not cancel its shipments.':action.next==='completed'?'All shipments must be delivered or failed before completion.':'Start this planned trip?'} submit={()=>trips.updateTripStatus(action.trip._id,{status:action.next})} refreshScopes={operationRefreshScopes.trip} onClose={()=>setAction(null)}/>}</div>
}
